blank_issues_enabled: true
contact_links:
  - name: Discord server
    url: invite.gg/pointerdevelopment
    about: Have questions or need support? Please go to the Discord server, as issues that are just support-related will be closed and redirected there.
